<a href="https://colab.research.google.com/github/javiermagnone-lab/Javito/blob/main/Taller_obligatorio_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Obligatorio 1
______________________________

Git-Hub: Guarda las versiones de los archivos, se edita en Colab

1-Para guardar ir a: Archivo > Guardar una copia en GitHub

2-En mensaje de confirmación le ponen lo que hicieron

3-Javito/Taller_obligatorio_1 se ve una vista Previa del codigo: https://github.com/javiermagnone-lab/Javito/blob/main/Taller_obligatorio_1.ipynb

4- A la derecha dice "History", con click ahi se muestran las versiones

## 01. Importar librerías y dataset

In [16]:
#Librerías

import pandas as pd
import numpy as np
import pandas as pd
import matplotlib
import matplotlib.pyplot as plt
import seaborn as sns

In [6]:
!pip install gdown

Requirement already satisfied: gdown in /usr/local/lib/python3.12/dist-packages (5.2.2)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.12/dist-packages (from gdown) (4.13.5)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from gdown) (3.29.0)
Requirement already satisfied: requests[socks] in /usr/local/lib/python3.12/dist-packages (from gdown) (2.32.4)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from gdown) (4.67.3)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4->gdown) (2.8.3)
Requirement already satisfied: typing-extensions>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4->gdown) (4.15.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests[socks]->gdown) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests[socks]->gdown) (3.13)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests[socks]->gdown) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests[socks]->gdown) (2026.4.22)
Requirement already satisfied: PySocks!=1.5.7,>=1.5.6 in /usr/local/lib/python3.12/dist-packages (from requests[socks]->gdown) (1.7.1)

In [11]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

## Carga del dataset de trabajo

In [12]:
# Carga del dataset

file_path = '/content/drive/MyDrive/Colab Notebooks/Taller Analitica de datos _Tarea/datos_optimizados (1).parquet'
df = pd.read_parquet(file_path)

DICCIONARIO CASO PEYA
- **order_id:** Identificador único de la orden en formato Hash (SHA256). Se utiliza para anonimizar el ID real y mantener la privacidad de la transacción.
- **product_id:** Identificador único del producto en formato Hash (SHA256). Permite distinguir productos individuales sin revelar su ID técnico original.
- **partner_id:** Identificador del vendor) en formato Hash (SHA256).
- **user_id:** Identificador único del user en formato Hash (SHA256).

Categorización y Producto

- **category:** Etiqueta de negocio asignada al producto (ej. "enlatados", "bebidas", "bebés").
- **business_type_name:** Tipo de unidad de negocio donde se realizó la compra (ej. 'Market', 'Kiosks' o 'Shop').

Temporalidad y Contexto

- **weekday:** Día de la semana en el que se registró la orden (en inglés, ej. 'Monday', 'Tuesday').
- **hour:** Hora del día (formato 0-23) en la que se realizó la transacción.

Métricas de la Orden

- **qty_total_products:** Cantidad total de ítems en el carrito.
- **total_amount:** Monto total de la orden.
- **has_discount:** Valor booleano (True/False). Indica si la orden tuvo algún tipo de descuento aplicado.

Perfil del Usuario

- **is_food:** Valor booleano (True/False). Indica si el usuario ha realizado pedidos de food anteriormente.
- **hist_qc_orders:** Histórico de pedidos que el usuario ha realizado en quick commerce.

## **01. Entendimiento de los datos**

In [13]:
#Lectura del dataset

df.head()

,order_id,product_id,category,weekday,hour,business_type_name,partner_id,user_id,qty_total_products,total_amount,has_discount,is_food,hist_qc_orders
0,PpTjCz6Rpezd61n5dPDJTuRqdeuei9ZF179usLRlHDo=,3PhxU90RAhdnzFLvK754zH8dCyaGhx+gRZK6FejN72c=,snacks,Wednesday,2,Kiosks,wGj5g/FyaoIGakOjc8rsSMKLP4ObLso+ToeBLz5gYXA=,MK8B+8oYcJV/UOWHXwSRZKONfUd4BeOoYDlqDfsf6G8=,4,29.047982,True,True,3857
1,b2fkJT7l609B1C5C4mOPpEGmJN9kFsFBEMfA1CFcg+Q=,nW7qzj8ZjWDhm9APVZBpQK+PZ5Rt8kpiJCw9OZ46FPA=,verduras,Wednesday,6,Market,boCBw+WzpRefsURSsXYnYGpr1HAK4RBUHV8hCmvGxGE=,xL2+iPNakXvX1le6s/sXR6QoP2FF44ZYziBWF9wvUNU=,32,185.701304,True,True,871
2,aRM17cbzgUQM2gYrzeKgZF5iPWe+4BoxGZzUR4I9u9M=,EA22Jy/uYTzJrbJZE0v70PUSzzUqzcP9vfWOVOctuJk=,quesos,Friday,7,Market,CSq+DtmiVKcNLprPiiWNTgH5sg97DimLHyswaz3tA5M=,Tk6M9oGhf9s7nUS0Lgf/cYArZLjpsFUnbQzFsQJB2Fc=,39,161.954034,True,True,198
3,ofBqN0N2C1oa7TclCSCS5PTJKTF4DWZJUA85gymH2rY=,P8NwM7gXFCIAeDJdyTCA2+LfcpTOFTi59ASuO7nmymg=,huevos,Friday,7,Market,CSq+DtmiVKcNLprPiiWNTgH5sg97DimLHyswaz3tA5M=,SJ9SEqbIILAEiKPrZ1+18MvW76IDBljdaYCT18wSjWA=,11,32.065813,True,True,246
4,0/7FYlHaqnXz2vaadJWARDRCjxDNRTgguABQXg/mlXc=,9nHMU4b5PPyfTH73olgbjZtx6hvcNtpZFSs1eXUJWb4=,productos de limpieza,Friday,7,Market,T4q47JhNP6vNeE2q/TgmqAJ+QQ1ryCWfr+virSVP8JA=,gI3OKl4ZOAL9N6+RsNfSxwx0oW4Ho3W3jO/KMt9pkqE=,11,25.598921,True,True,233

In [14]:
# Forma del dataset

df.shape

(15551102, 13)

In [15]:
#Lista a las columnas

columns = df.columns.values.tolist()
print(columns)

['order_id', 'product_id', 'category', 'weekday', 'hour', 'business_type_name', 'partner_id', 'user_id', 'qty_total_products', 'total_amount', 'has_discount', 'is_food', 'hist_qc_orders']

In [17]:
# Tabla con descripción general de las columnas

resumen = []
for col in df.columns:
    top_val = df[col].value_counts().idxmax() if df[col].count() > 0 else None
    top_pct = round(df[col].value_counts(normalize=True).max() * 100, 2) if df[col].count() > 0 else None

    resumen.append({
        'columna':             col,
        'tipo':                str(df[col].dtype),
        'total_valores':       df[col].count(),
        'valores_unicos':      df[col].nunique(),
        'nulos':               df[col].isnull().sum(),
        '% nulos':             round(df[col].isnull().mean() * 100, 2),
        'valor_mas_frecuente': str(top_val),
        '% mas_frecuente':     top_pct,
        'muestra':             str(df[col].dropna().unique()[:3].tolist())
    })

resumen_df = pd.DataFrame(resumen).set_index('columna')
resumen_df_original = resumen_df.copy()  # copia fija con nulos para exportar
resumen_df

,tipo,total_valores,valores_unicos,nulos,% nulos,valor_mas_frecuente,% mas_frecuente,muestra
columna,,,,,,,,
order_id,object,15092415,2474292,458687,2.95,cgocQnyCn9TodZwpf/pJyLgcFUkI+pBHWEoOKnAf72s=,0.00,['PpTjCz6Rpezd61n5dPDJTuRqdeuei9ZF179usLRlHDo=...
product_id,object,15551102,1545189,0,0.00,zMD29MXup2v/rYSi9yVqf2/hDUO+O2rmBPbfYrMR8bA=,0.03,['3PhxU90RAhdnzFLvK754zH8dCyaGhx+gRZK6FejN72c=...
category,object,15551102,62,0,0.00,pagnificados,7.57,"['snacks', 'verduras', 'quesos']"
weekday,object,15092415,7,458687,2.95,Sunday,17.78,"['Wednesday', 'Friday', 'Saturday']"
hour,Int64,15092415,24,458687,2.95,19,11.73,"[2, 6, 7]"
business_type_name,object,15092415,3,458687,2.95,Market,94.95,"['Kiosks', 'Market', 'Shop']"
partner_id,object,15092415,2261,458687,2.95,CSq+DtmiVKcNLprPiiWNTgH5sg97DimLHyswaz3tA5M=,2.07,['wGj5g/FyaoIGakOjc8rsSMKLP4ObLso+ToeBLz5gYXA=...
user_id,object,15092415,652879,458687,2.95,l7sBloJsG8eqTemjZSo29Fp6rhirzbKCoy3+hBzUCc4=,0.01,['MK8B+8oYcJV/UOWHXwSRZKONfUd4BeOoYDlqDfsf6G8=...
qty_total_products,Int64,15092415,176,458687,2.95,11,6.13,"[4, 32, 39]"
total_amount,float64,15092415,1146000,458687,2.95,0.0,0.17,"[29.04798181559177, 185.7013043720619, 161.954..."
has_discount,boolean,15092415,2,458687,2.95,True,92.73,"[True, False]"
is_food,boolean,15092415,2,458687,2.95,True,99.40,"[True, False]"
hist_qc_orders,Int64,15092415,4820,458687,2.95,146,0.18,"[3857, 871, 198]"

### **02. Auditoría de calidad de datos**

In [18]:
# Evaluo si los nulos son filas completas

nulos_por_fila = df.isnull().sum(axis=1)
dist = nulos_por_fila.value_counts().sort_index()

print("" * 45)
print(f"{'Columnas nulas por fila':<25} {'Cantidad de filas':>18}")
print("" * 45)
for n, cant in dist.items():
    pct = cant / len(df) * 100
    print(f"  {n:>2} columnas nulas {'':>10} {cant:>10,}  ({pct:.1f}%)")
print("" * 45)
print(f"\n✓ Solo existen filas con 0 ó {dist.index[-1]} columnas nulas.")
print(f"  Las {dist.iloc[-1]:,} filas sin order_id tienen TODAS")
print(f"  sus columnas de orden en nulo simultáneamente.")

Columnas nulas por fila    Cantidad de filas

   0 columnas nulas            15,092,415  (97.1%)
  11 columnas nulas               458,687  (2.9%)


✓ Solo existen filas con 0 ó 11 columnas nulas.
  Las 458,687 filas sin order_id tienen TODAS
  sus columnas de orden en nulo simultáneamente.

In [19]:
# Elimino las filas que tienen nulos

df_clean = df.dropna(subset=["order_id"]).reset_index (drop=True)
print(f"Filas originales: {len(df):,}")
print(f"Filas eliminadas: {len(df) - len(df_clean):,}")
print(f"Filas restantes: {len(df_clean):,}")

Filas originales: 15,551,102
Filas eliminadas: 458,687
Filas restantes: 15,092,415

In [20]:
# Duplicados exactos (toda la fila igual) - Evaluo erorr de carga del dataset

duplicados = df_clean[df_clean.duplicated(keep=False)]
print(f"Filas duplicadas: {len(duplicados):,}")

Filas duplicadas: 0

In [21]:
# Duplicados por clave: order_id + product_id

dup_clave = df_clean[df_clean.duplicated(subset=['order_id', 'product_id'], keep=False)]
print(f"Filas duplicadas por order_id + product_id: {len(dup_clave):,}")

Filas duplicadas por order_id + product_id: 0

In [22]:
#Copio el dataset

df = df_clean.copy()

In [23]:
# Mapeo de IDs.

id_cols = ['order_id', 'product_id', 'partner_id', 'user_id']

prefijos = {
    'order_id':   'ORD',
    'product_id': 'PRD',
    'partner_id': 'PTN',
    'user_id':    'USR'
}

for col in id_cols:
    mapping = {v: f"{prefijos[col]}_{i+1:05d}" for i, v in enumerate(df[col].unique())}
    df[col] = df[col].map(mapping)
df.head()

,order_id,product_id,category,weekday,hour,business_type_name,partner_id,user_id,qty_total_products,total_amount,has_discount,is_food,hist_qc_orders
0,ORD_00001,PRD_00001,snacks,Wednesday,2,Kiosks,PTN_00001,USR_00001,4,29.047982,True,True,3857
1,ORD_00002,PRD_00002,verduras,Wednesday,6,Market,PTN_00002,USR_00002,32,185.701304,True,True,871
2,ORD_00003,PRD_00003,quesos,Friday,7,Market,PTN_00003,USR_00003,39,161.954034,True,True,198
3,ORD_00004,PRD_00004,huevos,Friday,7,Market,PTN_00003,USR_00004,11,32.065813,True,True,246
4,ORD_00005,PRD_00005,productos de limpieza,Friday,7,Market,PTN_00004,USR_00005,11,25.598921,True,True,233

### **03.  Analisis Univariado**

In [24]:
### **04.  Analisis Bivariado**